### ISSUE TITLE
Supabase

### ISSUE THREAD

**Issue by znowfox** [swiftwave-org/app-store#1]
If supabase was installable and runnable in multiple instances with all functions working properly, like real-time (phoenix) in one click we would have a serious and solid case for self hosting developers, there is an army of devs on reddit waiting for this!

**Comment by tanmoysrt** [comment]
Added in the pending list https://github.com/orgs/swiftwave-org/discussions/568
Looking forward to make it available

**Comment by tanmoysrt** [comment]
> /build node-red 3.1-debian

_Ignore just for testing_

**Comment by tanmoysrt** [comment]
Closing as supabase has been added.
