### ISSUE TITLE
Pocketbase does not work on arm64

### ISSUE THREAD

**Issue by sneat** [swiftwave-org/app-store#15]
Running the one click install gives the `exec format error` when running on an `arm64` host.

I believe it is due to utilising the `amd64` release, rather than platform specific https://github.com/swiftwave-org/app-store/blob/main/build/pocketbase/0.22.13/Dockerfile#L10

**Comment by sneat** [comment]
Ticket can be closed I guess - I instead made it that my arm64 host was able to run amd64 images (utilising https://docs.docker.com/build/building/multi-platform/#qemu-without-docker-desktop)

**Comment by tanmoysrt** [comment]
Hi @sneat 
Missed this issue actually, will release the image for all the available arch

**Comment by tanmoysrt** [comment]
Hi @sneat 
Now, pocketbase 's imageavailable for all architecture natively.
https://github.com/swiftwave-org/app-store/pkgs/container/app-store%2Fpocketbase
